title: 福岡Ruby会議02
email: udzura@udzura.jp
description: 「もう一度、Rubyと出会う」をテーマに、大名小跡地Fukuoka growth nextで行う地域Ruby会議です。2017.11.25(Sat) 開催予定
baseurl: "/fukuoka02"
url: http://regional.rubykaigi.org/fukuoka02/
twitter_username: fukuokark
github_username:  fukuokark
#github_url: https://fukuokarb.connpass.com/
  

# Build settings
permalink: :title
paginate: 1
paginate_path: "page:num"
kramdown:
  input: GFM
  hard_wrap: false
highlighter: rouge
gems:
  - jekyll-feed
  - jekyll-paginate
exclude:
  - Gemfile
  - Gemfile.lock
